name: Scheduled Auto Merge From Develop To Staging

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git status
      - run: git branch
