name: Auto Merge From Develop To Staging

on:
  schedule:
    - cron: '05 * * * *'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          head_to_merge: develop
          target_branch: staging
          github_token: ${{ github.token }}
