name: Scheduled build

on:
  schedule:
    - cron: '30 7 * * *'

jobs:
  chk-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git status
      - run: git branch
